//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH_XEMAYMVC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public long Idchitiet { get; set; }
        public long Maxe { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public int soluong { get; set; }
        public Nullable<long> DonHang_Id { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual XeMay XeMay { get; set; }
    }
}
