//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH_XEMAYMVC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        public DanhMuc()
        {
            this.LienHes = new HashSet<LienHe>();
            this.Posts = new HashSet<Post>();
            this.TinTucs = new HashSet<TinTuc>();
        }
    
        public long Id { get; set; }
        public string Tieude { get; set; }
        public string mota { get; set; }
        public int position { get; set; }
        public string seotieude { get; set; }
        public string seomota { get; set; }
        public string seotukhoa { get; set; }
        public System.DateTime ngaytao { get; set; }
        public string nguoitao { get; set; }
        public System.DateTime ngaysua { get; set; }
        public string nguoisua { get; set; }
        public string alias { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<LienHe> LienHes { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<TinTuc> TinTucs { get; set; }
    }
}
