//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH_XEMAYMVC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageX
    {
        public long id { get; set; }
        public long idsanpham { get; set; }
        public string image { get; set; }
        public bool isdefault { get; set; }
        public Nullable<long> Xemay_Maxe { get; set; }
    
        public virtual XeMay XeMay { get; set; }
    }
}
