//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH_XEMAYMVC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string message { get; set; }
        public bool isread { get; set; }
        public System.DateTime ngaytao { get; set; }
        public string nguoitao { get; set; }
        public System.DateTime ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<long> DanhMuc_Id { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
