//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH_XEMAYMVC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public long Id { get; set; }
        public string Tieude { get; set; }
        public long Iddanhmuc { get; set; }
        public string mota { get; set; }
        public string chitiet { get; set; }
        public string image { get; set; }
        public string seotieude { get; set; }
        public string seomota { get; set; }
        public string seotukhoa { get; set; }
        public System.DateTime ngaytao { get; set; }
        public string nguoitao { get; set; }
        public System.DateTime ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<long> DanhMuc_Id { get; set; }
        public string alias { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
