//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH_XEMAYMVC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeMay
    {
        public XeMay()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.ImageXes = new HashSet<ImageX>();
        }
    
        public long Maxe { get; set; }
        public string Tenxe { get; set; }
        public Nullable<decimal> Giaxe { get; set; }
        public Nullable<decimal> Giasale { get; set; }
        public string mota { get; set; }
        public string chitiet { get; set; }
        public string anh { get; set; }
        public string soluong { get; set; }
        public long Iddanhmuc { get; set; }
        public long maxuatxu { get; set; }
        public long manhanhieu { get; set; }
        public System.DateTime ngaytao { get; set; }
        public string nguoitao { get; set; }
        public System.DateTime ngaysua { get; set; }
        public string nguoisua { get; set; }
        public Nullable<long> DanhMucSanPham_Id { get; set; }
        public string alias { get; set; }
        public bool IsHome { get; set; }
        public bool IsSale { get; set; }
        public bool IsFeature { get; set; }
        public bool IsHot { get; set; }
        public bool IsActive { get; set; }
        public string seotieude { get; set; }
        public string seomota { get; set; }
        public string seotukhoa { get; set; }
        public string Codesanpham { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMucSanPham DanhMucSanPham { get; set; }
        public virtual ICollection<ImageX> ImageXes { get; set; }
        public virtual NhanHieu NhanHieu { get; set; }
        public virtual XuatXu XuatXu { get; set; }
    }
}
