//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH_XEMAYMVC.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XuatXu
    {
        public XuatXu()
        {
            this.XeMays = new HashSet<XeMay>();
        }
    
        public long maxuatxu { get; set; }
        public string tenxuatxu { get; set; }
    
        public virtual ICollection<XeMay> XeMays { get; set; }
    }
}
